# Generated by Django 3.1.7 on 2021-03-04 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210304_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='klub',
            name='liga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.liga'),
        ),
    ]
