# Generated by Django 3.1.7 on 2021-03-05 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210304_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=32)),
                ('nazwisko', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='piłkarz',
            name='pozycja',
            field=models.CharField(choices=[('Tam gdzie trzeba', 'Tam gdzie trzeba'), ('Obrońca', 'Obrońca'), ('Napastnik', 'Napastnik'), ('Pomocnik', 'Pomocnik'), ('Bramkarz', 'Bramkarz')], default='Tam gdzie trzeba', max_length=32),
        ),
        migrations.AddField(
            model_name='piłkarz',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.agent'),
        ),
    ]
