# Generated by Django 3.1.7 on 2021-03-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210305_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piłkarz',
            name='klub',
        ),
        migrations.AddField(
            model_name='klub',
            name='piłkarz',
            field=models.ManyToManyField(to='api.Piłkarz'),
        ),
        migrations.AlterField(
            model_name='piłkarz',
            name='pozycja',
            field=models.CharField(choices=[('Bramkarz', 'Bramkarz'), ('Tam gdzie trzeba', 'Tam gdzie trzeba'), ('Pomocnik', 'Pomocnik'), ('Napastnik', 'Napastnik'), ('Obrońca', 'Obrońca')], default='Tam gdzie trzeba', max_length=32),
        ),
    ]
