# Generated by Django 3.1.7 on 2021-03-05 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210305_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klub',
            name='piłkarz',
        ),
        migrations.AddField(
            model_name='klub',
            name='piłkarz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.piłkarz'),
        ),
        migrations.AlterField(
            model_name='piłkarz',
            name='pozycja',
            field=models.CharField(choices=[('Obrońca', 'Obrońca'), ('Bramkarz', 'Bramkarz'), ('Napastnik', 'Napastnik'), ('Pomocnik', 'Pomocnik'), ('Tam gdzie trzeba', 'Tam gdzie trzeba')], default='Tam gdzie trzeba', max_length=32),
        ),
    ]
