# Generated by Django 3.1.7 on 2021-03-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210305_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='piłkarz',
            name='czy_aktywny',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='piłkarz',
            name='pozycja',
            field=models.CharField(choices=[('Tam gdzie trzeba', 'Tam gdzie trzeba'), ('Napastnik', 'Napastnik'), ('Obrońca', 'Obrońca'), ('Bramkarz', 'Bramkarz'), ('Pomocnik', 'Pomocnik')], default='Tam gdzie trzeba', max_length=32),
        ),
    ]
