# Generated by Django 3.1.7 on 2021-03-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210307_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piłkarz',
            name='pozycja',
            field=models.CharField(choices=[('Napastnik', 'Napastnik'), ('Obrońca', 'Obrońca'), ('Tam gdzie trzeba', 'Tam gdzie trzeba'), ('Pomocnik', 'Pomocnik'), ('Bramkarz', 'Bramkarz')], default='Tam gdzie trzeba', max_length=32),
        ),
    ]
